---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-app-configmap
data:
  REDMINE_DB_POSTGRES: redmine-postgres
  REDMINE_DB_DATABASE: redmine
  REDMINE_DB_USERNAME: redmine
  REDMINE_DB_PASSWORD: nyan
  REDMINE_DB_ENCODING: utf8
---
apiVersion: v1
kind: Pod
metadata:
  name: redmine-app
spec:
  containers:
  - name: redmine
    image: redmine
    envFrom:
    - configMapRef:
        name: redmine-app-configmap  
    volumeMounts:
      - mountPath: /usr/src/redmine/files
        name: redmine-app-files
      - mountPath: /usr/src/redmine/log
        name: redmine-app-log
      - mountPath: /usr/src/redmine/plugins
        name: redmine-app-plugins
      - mountPath: /usr/src/redmine/themes
        name: redmine-app-themes
    securityContext:
      privileged: true
  volumes:
    - name: redmine-app-files
      persistentVolumeClaim:
        claimName: redmine-app-files-pvc
    - name: redmine-app-log
      persistentVolumeClaim:
        claimName: redmine-app-log-pvc
    - name: redmine-app-plugins
      persistentVolumeClaim:
        claimName: redmine-app-plugins-pvc
    - name: redmine-app-themes
      persistentVolumeClaim:
        claimName: redmine-app-themes-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-app-files-pv
  labels:
    name: redmine-app-files-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/test/files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-app-files-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: redmine-app-files-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-app-log-pv
  labels:
    name: redmine-app-log-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/test/log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-app-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: redmine-app-log-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-app-plugins-pv
  labels:
    name: redmine-app-plugins-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/test/plugins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-app-plugins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: redmine-app-plugins-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-app-themes-pv
  labels:
    name: redmine-app-themes-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/test/themes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-app-themes-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: redmine-app-themes-pv