apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  selector:
    matchLabels:
      name: redmine-db-pv