---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:
    processors:
      attributes:
        actions:
          - key: service.environment
            value: add-from-otel
            action: insert
    exporters:
      # logging:
      # otlp:
      #   endpoint: "http://192.168.11.38:8200"
      #   tls:
      #     insecure: true
      elastic:
        apm_server_url: "http://192.168.11.38:8200"
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging, otlp]
        traces:
          receivers: [otlp]
          processors: [attributes]
          exporters: [elastic]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrycollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetrycollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetrycollector
    spec:
      containers:
      - name: otelcol
        args:
        - --config=/conf/collector.yaml
        image: otel/opentelemetry-collector:0.80.0
        volumeMounts:
        - mountPath: /conf
          name: collector-config
      volumes:
      - configMap:
          items:
          - key: collector.yaml
            path: collector.yaml
          name: collector-config
        name: collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector-http
spec:
  ports:
  - name: http-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector-lb-http
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.131
  ports:
    - name: http-otlp
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app.kubernetes.io/name: opentelemetrycollector
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector-grpc
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector-lb-grpc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.132
  ports:
    - name: http-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
  selector:
    app.kubernetes.io/name: opentelemetrycollector