---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-postgres-configmap
data:
  POSTGRES_DB: redmine
  POSTGRES_USER: redmine
  POSTGRES_PASSWORD: nyan
---
apiVersion: v1
kind: Pod
metadata:
  name: redmine-postgres
spec:
  containers:
  - name: postgres
    image: postgres
    envFrom:
    - configMapRef:
        name: redmine-postgres-configmap  
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: redmine-postgres-vol
  volumes:
    - name: redmine-postgres-vol
      persistentVolumeClaim:
        claimName: redmine-postgres-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-postgres-pv
  labels:
    name: redmine-postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/redmine/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: redmine-postgres-pv
