apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-files-pv
  labels:
    name: redmine-files-pv
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.30
    path: /export/hdd1/redmine/files
