apiVersion: v1
data:
  mariadb-password: YXFJTGF4dDNvSQ==
  mariadb-root-password: MEtVT3I3QmFSRA==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: redmine
  creationTimestamp: "2020-11-08T06:44:38Z"
  labels:
    app: mariadb
    app.kubernetes.io/managed-by: Helm
    chart: mariadb-7.10.4
    heritage: Helm
    release: my-release
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mariadb-password: {}
        f:mariadb-root-password: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-11-08T06:44:38Z"
  name: my-release-mariadb
  namespace: redmine
  resourceVersion: "7947270"
  selfLink: /api/v1/namespaces/redmine/secrets/my-release-mariadb
  uid: 4360468c-7821-4238-958d-d9418c98fb30
type: Opaque
