apiVersion: v1
data:
  redmine-password: U2h3STVibDZVYw==
  smtp-password: ""
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: redmine
  creationTimestamp: "2020-11-08T06:44:38Z"
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redmine
    helm.sh/chart: redmine-14.2.13
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:redmine-password: {}
        f:smtp-password: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:helm.sh/chart: {}
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-11-08T06:44:38Z"
  name: my-release-redmine
  namespace: redmine
  resourceVersion: "7947269"
  selfLink: /api/v1/namespaces/redmine/secrets/my-release-redmine
  uid: 5a315051-f537-4e04-9f9d-bbd4a111477a
type: Opaque
