---
apiVersion: v1
kind: Pod
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  containers:
    - name: minecraft-server
      image: itzg/minecraft-server:1.8.0-multiarch
      env:
      - name: EULA
        value: "TRUE"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 25565
    targetPort: 25565
    nodePort: 30100
  selector:
    app: minecraft-server
