---
apiVersion: v1
kind: Pod
metadata:
  name: minecraft-server2
  labels:
    app: minecraft-server2
spec:
  containers:
    - name: minecraft-server2
      image: itzg/minecraft-server:1.8.0-multiarch
      env:
      - name: EULA
        value: "TRUE"
      volumeMounts:
      - mountPath: "/data"
        name: minecraft-volume2
  volumes:
    - name: minecraft-volume2
      persistentVolumeClaim:
        claimName: minecraft-pvc2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb2
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 25565
    targetPort: 25565
    nodePort: 30101
  selector:
    app: minecraft-server2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /data/pv001
    type: DirectoryOrCreate
