---
apiVersion: v1
kind: Pod
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  containers:
    - name: minecraft-server
      image: itzg/minecraft-server:1.8.0-multiarch
      env:
      - name: EULA
        value: "TRUE"
      volumeMounts:
      - mountPath: "/data"
        name: minecraft-volume
  volumes:
    - name: minecraft-volume
      persistentVolumeClaim:
        claimName: minecraft-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 25565
    targetPort: 25565
    nodePort: 30100
  selector:
    app: minecraft-server
