---
apiVersion: v1
kind: Pod
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  containers:
    - name: minecraft-server
      image: itzg/minecraft-server:latest
      env:
      - name: EULA
        value: "TRUE"
      volumeMounts:
      - mountPath: "/data"
        name: minecraft-volume
  volumes:
    - name: minecraft-volume
      persistentVolumeClaim:
        claimName: minecraft-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/minecraft/0001
    type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.11.130
  ports:
  - protocol: "TCP"
    port: 25565
    targetPort: 25565
  selector:
    app: minecraft-server
