---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-app-configmap
data:
  REDMINE_DB_POSTGRES: redmine-postgres
  REDMINE_DB_DATABASE: redmine
  REDMINE_DB_USERNAME: redmine
  REDMINE_DB_PASSWORD: nyan
  REDMINE_DB_ENCODING: utf8
---
apiVersion: v1
kind: Pod
metadata:
  name: redmine-app
  labels:
    app: redmine-app
spec:
  containers:
  - name: redmine
    image: redmine
    envFrom:
    - configMapRef:
        name: redmine-app-configmap  
#    volumeMounts:
#      - mountPath: /usr/src/redmine
#        name: redmine-app-vol
    securityContext:
      privileged: true
#  volumes:
#    - name: redmine-app-vol
#      persistentVolumeClaim:
#        claimName: redmine-app-pvc
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: redmine-app-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-lb
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
    nodePort: 30394
  selector:
    app: redmine-app