---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redmine-db
spec:
  selector:
    matchLabels:
      app: redmine-db
  serviceName: redmine-db
  replicas: 1
  template:
    metadata:
      name: redmine-db
      labels:
        app: redmine-db
    spec:
      containers:
      - name: mariadb
        envFrom:
        - configMapRef:
            name: redmine-db-configmap
        - secretRef:
            name: redmine-db-secret
        image: docker.io/library/mariadb
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          seLinuxOptions: {}
        workingDir: /
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-volume
  volumeClaimTemplates:
  - metadata:
      name: db-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redmine-db