apiVersion: v1
kind: PersistentVolume
metadata:
  name: concourse-postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/0001"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: concourse-worker-pv-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/0002"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: concourse-worker-pv-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/0003"
