---
apiVersion: v1
kind: Pod
metadata:
  name: redmine-db
  labels:
    app: redmine-db
spec:
  containers:
  - name: mariadb
    envFrom:
    - configMapRef:
        name: redmine-db-configmap
    - secretRef:
        name: redmine-db-secret
    image: docker.io/library/mariadb
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: db-volume
  volumes:
  - name: db-volume
    persistentVolumeClaim:
      claimName: redmine-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redmine-db