---
apiVersion: v1
kind: Endpoints
metadata:
    name: concourse-metrics-endpoint
    labels:
        release: prometheus-operator
    namespace: monitoring
subsets:
    - addresses:
      - ip: 192.168.11.110
      ports:
      - name: metrics
        port: 30200
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
    name: concourse-metrics-endpoint
    namespace: monitoring
    labels:
        release: prometheus-operator
        k8s-app: concourse-metrics
spec:
    type: ExternalName
    externalName: 192.168.11.110
    ports:
    - name: metrics
      port: 30200
      protocol: TCP
      targetPort: 30200
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: concurse-metrics-sm
    labels:
        release: prometheus-operator
        prometheus: kube-prometheus
    namespace: monitoring
spec:
    selector:
        matchLabels:
            release: prometheus-operator
            k8s-app: concourse-metrics
    endpoints:
    - port: metrics
      interval: 10s
      honorLabels: true
      path: /metrics