resources:
- name: timer
  type: time
  source:
    interval: 2m

jobs:
- name: hello-world?
  plan:
  - get: timer
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["Hello, world!"]
