---
resources:
  - name: tutorial
    type: git
    source:
      uri: https://github.com/drnic/concourse-tutorial.git
      branch: develop

  - name: hello-world-docker-image
    type: docker-image
    source:
      email: tricolore_kp_51@icloud.com
      username: gaki65
      password: tr_kp_514021
      repository: gaki65/concourse-tutorial-hello-world

jobs:
  - name: publish
    public: true
    plan:
      - get: tutorial
      - put: hello-world-docker-image
        params:
          build: tutorial/tutorials/miscellaneous/docker-images/docker
      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: gaki65/concourse-tutorial-hello-world
          run:
            path: /bin/hello-world
            args: []
          params:
            NAME: gaki65
