apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-chartmuseum-pv
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/1001"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice-pv
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/1002"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry-pv
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/1003"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-dbdata-pv
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/1004"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-data-pv
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/1005"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-data2-pv
  labels:
    type: local
spec:
#  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/1006"
---