apiVersion: v1
data:
  my.cnf: |-
    [mysqld]
    datadir=/var/lib/mysql
    socket=/var/lib/mysql/mysql.sock
    character-set-server=utf8

    [mysqld_safe]
    log-error=/var/log/mariadb/mariadb.log
    pid-file=/var/run/mariadb/mariadb.pid

    [mysql]
    default-character-set=utf8

kind: ConfigMap
metadata:
  labels:
    app: mariadb
  name: mariadb-configmap
  namespace: redmine