apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
    - name: mariadb
      image: mariadb
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: nyanpass
      volumeMounts:
      - mountPath: /etc/mysql/my.cnf
        name: config
        subPath: my.cnf
  volumes:
  - configMap:
      defaultMode: 420
      name: mariadb-configmap
    name: config