name: deploy-manifests
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Changed Files
        id  : get_changed_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: json
      - name: Filter Files
        id  : filter_files
        run : |
          echo "::set-output name=filtered_files::$(jq -r -j --argjson added_modified '${{ steps.get_changed_files.outputs.added_modified }}' --argjson renamed '${{ steps.get_changed_files.outputs.renamed }}' -n '$added_modified + $renamed | map(select(test("deployments/"))) | map(select(test("TEMPLATE") | not)) | map(select(test(".(?i)(yml|yaml)$"))) | map(" -f " + . + " ")[]')"
      - name: Print Filtered Files
        run : |
          echo 'Filtered Files :'
          echo "${{ steps.filter_files.outputs.filtered_files }}"
      - name: Deploy Files With Kubernetes CLI
        if  : steps.filter_files.outputs.filtered_files != null && steps.filter_files.outputs.filtered_files != ''
        run : |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > /tmp/config
          export KUBECONFIG=/tmp/config
          kubectl apply ${{ steps.filter_files.outputs.filtered_files }}
